### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile. 

### ISSUE THREAD

**Issue by nathanbaleeta** [unicef/invent#23]
Basing on the [developer documentation](https://unicef-invent.readthedocs.io/en/latest/installation_manual.html) linked above, I would like to build containers using command `docker-compose build`, however I'm returned with the following `ERROR: Cannot locate specified Dockerfile: Dockerfile`

@mgaliatsatou @pvlontzos could you please share any workarounds to fixing this?

cc: @ewheeler

**Comment by gkalomalos** [comment]
Hi @nathanbaleeta. We are in the middle of the building process of the application for local development from using docker-compose to Tilt. The process will be publicly available and fully documented in the upcoming weeks. 

For the time being you could try to follow these steps and let us know if there's an issue with the building process:
Prerequisites:
Docker

Configuration:
	1. Clone the project
	2. **Checkout to master branch**
	3. Create a .env file in the frontend folder, based on the .env.template that's already present, with at least these values:
		HOST=localhost
		PORT=3000
		NODE_ENV=dev
	4. Create a .env file in the backend folder, based on the .env.template that's already present, with at least these values:
		SECRET_KEY=
		DEBUG=False
		PROJECT_NAME=
		REDIS_URL=redis
		SIMPLE_FEEDBACK_SEND_TO=
		API_MAINTAINER=
	5. Inside the **root invent directory** execute:
		○ docker-compose build
                ○ docker-compose up

**Comment by nathanbaleeta** [comment]
> Hi @nathanbaleeta. We are in the middle of the building process of the application for local development from using docker-compose to Tilt. The process will be publicly available and fully documented in the upcoming weeks.
> 
> For the time being you could try to follow these steps and let us know if there's an issue with the building process: Prerequisites: Docker
> 
> Configuration: 1. Clone the project 2. **Checkout to master branch** 3. Create a .env file in the frontend folder, based on the .env.template that's already present, with at least these values: HOST=localhost PORT=3000 NODE_ENV=dev 4. Create a .env file in the backend folder, based on the .env.template that's already present, with at least these values: SECRET_KEY= DEBUG=False PROJECT_NAME= REDIS_URL=redis SIMPLE_FEEDBACK_SEND_TO= API_MAINTAINER= 5. Inside the **root invent directory** execute: ○ docker-compose build ○ docker-compose up

Hi @gkalomalos, it finally worked! Thanks a bunch.

**Comment by gkalomalos** [comment]
Great! Closing this issue.
